INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(07, 'earn_type_7');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(21, 'earn_type_21');

INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(11, 'earn_type_11');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(12, 'earn_type_12');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(13, 'earn_type_13');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(14, 'earn_type_14');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(15, 'earn_type_15');

INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(16, 'TRAVEL_earn_type_16');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(17, 'TRAVEL_earn_type_17');

INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(16, 'TRAVEL_earn_type_16_1');
INSERT INTO EARN_TYPE(EARN_TYPE_CODE, EARN_TYPE_NAME) VALUES(17, 'TRAVEL_earn_type_17_1');